SELECT A.COMPANY_CODE, B.FOUNDER,
    COUNT(DISTINCT A.lead_manager_code) R1, 
    COUNT(DISTINCT A.senior_manager_code) R2,
    COUNT(DISTINCT A.manager_code) R3, 
    COUNT(DISTINCT A.employee_code) R4
FROM EMPLOYEE A JOIN COMPANY B 
ON A.COMPANY_CODE = B.COMPANY_CODE
GROUP BY A.COMPANY_CODE, B.FOUNDER
ORDER BY A.COMPANY_CODE;