SELECT 
    MAX(CASE WHEN OCCUPATION = 'Doctor' THEN NAME END) as Doctor, 
    MAX(CASE WHEN OCCUPATION = 'Professor' THEN NAME END) as Professor, 
    MAX(CASE WHEN OCCUPATION = 'Singer' THEN NAME END) as Singer,  
    MAX(CASE WHEN OCCUPATION = 'Actor' THEN NAME END) as Actor
FROM (
    SELECT *, ROW_NUMBER() OVER(
        PARTITION BY OCCUPATION
        ORDER BY NAME) AS RNK 
    FROM OCCUPATIONS) AS BASE 
GROUP BY RNK;